# Generated by Django 4.2.3 on 2024-05-03 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
